id: ID229B8DD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:12:29+00:00'
last_modified: '2022-06-16T06:04:43.864574+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22096
  title: གསུང་འབུམ། འགྱུར་མེད་རྡོ་རྗེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    328E:
      image_group_id: I2195
      title: ''
      total_pages: 726
      order: 1
      base_file: 328E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
