id: ID229B8DD
legacy_id: P008008
ocr_import_info:
  bdrc_scan_id: W22096
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T21:08:27'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:30:18.630050+00:00'
last_modified: 2022-09-02 04:34:10.138102
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22096
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW22096
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། འགྱུར་མེད་རྡོ་རྗེ།
  author: གཏེར་བདག་གླིང་པ་འགྱུར་མེད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.9080708544510856
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I2198:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2198
      total_pages: 614
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2198.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9268587038048313
    legacy_id: v004
  I2202:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2202
      total_pages: 730
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2202.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9083035285287475
    legacy_id: v008
  I2210:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2210
      total_pages: 766
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I2210.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.908432320534218
    legacy_id: v016
  I2196:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2196
      total_pages: 644
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2196.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9206602773480553
    legacy_id: v002
  I2195:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2195
      total_pages: 726
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2195.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.921528477949821
    legacy_id: v001
  I2207:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2207
      total_pages: 784
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I2207.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9016990023050611
    legacy_id: v013
  I2205:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2205
      total_pages: 746
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I2205.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8732504725164222
    legacy_id: v011
  I2201:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2201
      total_pages: 772
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2201.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9012118174274196
    legacy_id: v007
  I2197:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2197
      total_pages: 668
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2197.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9101294435078752
    legacy_id: v003
  I2200:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2200
      total_pages: 690
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2200.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9207390170871906
    legacy_id: v006
  I2204:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2204
      total_pages: 724
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I2204.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9054418530490169
    legacy_id: v010
  I2208:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2208
      total_pages: 666
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I2208.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9086386839232983
    legacy_id: v014
  I2206:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2206
      total_pages: 674
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I2206.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8662944182305287
    legacy_id: v012
  I2209:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2209
      total_pages: 602
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I2209.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9083873715346483
    legacy_id: v015
  I2203:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2203
      total_pages: 782
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I2203.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8981469424682793
    legacy_id: v009
  I2199:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2199
      total_pages: 634
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2199.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9187883945851864
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
